/**
 * 🎨 API
 * Serves data for our projects
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CubeSuggestion { 
    /**
     * InscriptionId for Side 1
     */
    inscriptionId1: string;
    /**
     * InscriptionId for Side 2
     */
    inscriptionId2: string;
    /**
     * InscriptionId for Side 3
     */
    inscriptionId3: string;
    /**
     * InscriptionId for Side 4
     */
    inscriptionId4: string;
    /**
     * InscriptionId for Side 5
     */
    inscriptionId5: string;
    /**
     * InscriptionId for Side 6
     */
    inscriptionId6: string;
    /**
     * Name of the Collection
     */
    collectionName: string;
    /**
     * Symbol of the Collection
     */
    collectionSymbol: string;
}

