/**
 * 🎨 API
 * Serves data for our projects
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InscriptionExtendedSingleResultInscription } from './inscriptionExtendedSingleResultInscription';


export interface InscriptionExtendedSingleResult { 
    inscription: InscriptionExtendedSingleResultInscription;
    /**
     * Previous inscriptionId of a sorted list OR NULL
     */
    previousInscriptionId: string;
    /**
     * Next inscriptionId of a sorted list OR NULL
     */
    nextInscriptionId: string;
}

