/**
 * 🎨 API
 * Serves data for our projects
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MintRequest { 
    /**
     * The contract to interact with
     */
    tokenName: MintRequest.TokenNameEnum;
    /**
     * The msg.sender that will interact with the contract
     */
    sender: string;
}
export namespace MintRequest {
    export type TokenNameEnum = 'genesis' | 'mosaic' | 'sea' | 'art' | 'artist' | 'cube';
    export const TokenNameEnum = {
        Genesis: 'genesis' as TokenNameEnum,
        Mosaic: 'mosaic' as TokenNameEnum,
        Sea: 'sea' as TokenNameEnum,
        Art: 'art' as TokenNameEnum,
        Artist: 'artist' as TokenNameEnum,
        Cube: 'cube' as TokenNameEnum
    };
}


