#!/usr/bin/env bash
# Inscribe the committed fixture bytes onto the regtest chain and write their
# ids to src/environments/regtest-inscriptions.generated.ts.
#
# The app requests `/content/<id>` for the cube renderer and for every unfilled
# side. Those ids are part of the minted bytes and of the preview, so on regtest
# they have to exist on THIS chain: a mainnet id there is a request the stack
# cannot answer, which is what the deleted console-error allowlist was hiding.
#
# Ids are not stable across bootstraps (they depend on the funding txids), so
# the generated file is gitignored and rewritten on every run.
#
# Usage:  ./e2e/regtest/inscribe-fixtures.sh
# Reads:  E2E_PREFIX (default cubes-e2e), E2E_ORD_STOCK_HOST_PORT (default 8081)
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
APP="$(cd "$HERE/../.." && pwd)"
PREFIX="${E2E_PREFIX:-cubes-e2e}"
ORD_PORT="${E2E_ORD_STOCK_HOST_PORT:-8081}"
OUT="$APP/src/environments/regtest-inscriptions.generated.ts"

BTC() { docker exec "${PREFIX}-bitcoind" bitcoin-cli -regtest -rpcuser=ordpool -rpcpassword=ordpool "$@"; }
# `--no-backup` is load-bearing: ord's recovery-key import (`importdescriptors`
# of the commit key) fails against Bitcoin Core v30 with "commit tx recovery key
# import failed", and the backup is worthless for a throwaway regtest chain.
ORD() {
  docker exec "${PREFIX}-ord-stock" ord --regtest \
    --bitcoin-rpc-url=bitcoind:18443 --bitcoin-rpc-username=ordpool --bitcoin-rpc-password=ordpool \
    --data-dir=/data wallet --server-url http://127.0.0.1:8080 "$@"
}

# ord refuses every wallet command while its index trails bitcoind, so each
# mine is followed by a wait rather than a sleep.
wait_for_ord_sync() {
  local want; want="$(BTC getblockcount)"
  for _ in $(seq 1 60); do
    if [ "$(curl -fsS -H 'Accept: application/json' "http://127.0.0.1:${ORD_PORT}/blockheight" 2>/dev/null || echo -1)" = "$want" ]; then return 0; fi
    sleep 1
  done
  echo "ord-stock did not reach height $want" >&2; exit 1
}

# --- an ord wallet with mature funds -------------------------------------
if ! ORD balance >/dev/null 2>&1; then
  ORD create >/dev/null
fi
if [ "$(ORD balance | python3 -c 'import sys,json;print(json.load(sys.stdin)["cardinal"])')" -lt 10000000 ]; then
  ADDR="$(ORD receive | python3 -c 'import sys,json;print(json.load(sys.stdin)["addresses"][0])')"
  BTC -rpcwallet="${PREFIX}" sendtoaddress "$ADDR" 1 >/dev/null
  BTC -rpcwallet="${PREFIX}" -generate 1 >/dev/null
  wait_for_ord_sync
fi

# --- inscribe every fixture ----------------------------------------------
docker exec "${PREFIX}-ord-stock" rm -rf /fixtures
docker cp "$HERE/fixtures" "${PREFIX}-ord-stock:/fixtures" >/dev/null

# ord only spends CONFIRMED cardinal utxos, so every inscription's change has
# to be mined before the next one can be funded from it. Without the mine the
# second inscribe fails with "wallet contains no cardinal utxos" while the
# change sits unconfirmed in bitcoind.
inscribe() {
  local id
  id="$(ORD inscribe --fee-rate 1 --no-backup --file "/fixtures/$1" \
    | python3 -c 'import sys,json;print(json.load(sys.stdin)["inscriptions"][0]["id"])')"
  BTC -rpcwallet="${PREFIX}" -generate 1 >/dev/null
  wait_for_ord_sync
  echo "$id"
}

RENDERER="$(inscribe cube-renderer.js)"
SIDES=()
for n in 1 2 3 4 5 6; do SIDES+=("$(inscribe "side-$n.png")"); done
NON_IMAGE="$(inscribe non-image.json)"

# --- write the generated module ------------------------------------------
{
  echo "// GENERATED by e2e/regtest/inscribe-fixtures.sh. Do not edit, do not commit."
  echo "// Regtest inscription ids depend on the funding txids, so they change with"
  echo "// every fresh chain. The bytes behind them are the committed fixtures in"
  echo "// e2e/regtest/fixtures/, byte-identical to their mainnet originals."
  echo "export const regtestInscriptions = {"
  echo "  cubeRenderer: '$RENDERER',"
  echo "  fallbackSides: ["
  for id in "${SIDES[@]}"; do echo "    '$id',"; done
  echo "  ],"
  echo "  nonImageSide: '$NON_IMAGE',"
  echo "};"
} > "$OUT"

echo "wrote $OUT" >&2
cat "$OUT" >&2
