#!/usr/bin/env node
/**
 * Build-time env injection for cubes-frontend.
 *
 * Reads `HAUSHOPPE_TIP_ADDRESS` (and optional `HAUSHOPPE_TIP_SATS`) from
 * process.env, generates `src/environments/environment.prod.generated.ts`
 * from `src/environments/environment.prod.ts` (the committed template
 * that still carries the `'???'` placeholder), and writes the concrete
 * value into the generated file.
 *
 * `angular.json` production config's `fileReplacements` swap
 * `environment.ts` -> `environment.prod.generated.ts`, so the compiled
 * bundle picks up the injected address.
 *
 * Missing / malformed env var:
 *   - In CI (CI=true): exit 1 with a clear error message.
 *   - Locally (CI unset): write the `'???'` placeholder as-is with a
 *     stderr warning so `npm run build` doesn't fail on a dev laptop.
 *     The main.ts boot-time sanity check catches the placeholder at
 *     runtime for any prod build that still carries it.
 *
 * Regtest and dev use their own environment files (`environment.regtest.ts`,
 * `environment.ts`) which carry valid regtest addresses; this script
 * touches only the prod-generated file.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const TEMPLATE = resolve(HERE, '..', 'src', 'environments', 'environment.prod.ts');
const OUT = resolve(HERE, '..', 'src', 'environments', 'environment.prod.generated.ts');

const isCi = process.env.CI === 'true' || process.env.GITHUB_ACTIONS === 'true';

const tipAddress = (process.env.HAUSHOPPE_TIP_ADDRESS ?? '').trim();
const tipSatsRaw = (process.env.HAUSHOPPE_TIP_SATS ?? '').trim();

/**
 * Cheap shape check: any real mainnet Bitcoin address (P2TR, P2WPKH,
 * P2WSH, P2SH, P2PKH). Full checksum + network validation runs at
 * boot in main.ts via ordpool-sdk's getAddressFormat +
 * getAddressNetwork; this script only rejects obvious garbage so
 * the build fails early with a helpful error instead of running to
 * ng-build.
 */
function looksLikeMainnetAddress(addr) {
  if (!addr || /\s/.test(addr)) return false;
  // bech32 / bech32m mainnet: `bc1` + [pqzr…] (SegWit v0 P2WPKH/P2WSH,
  // SegWit v1 P2TR). Length range covers P2WPKH (42) through P2WSH (62).
  if (addr.startsWith('bc1')) {
    return addr.length >= 42 && addr.length <= 62
      && /^bc1[qpzry9x8gf2tvdw0s3jn54khce6mua7l]+$/.test(addr);
  }
  // Legacy base58: P2PKH `1...` or P2SH `3...`. Length 26-35.
  if (/^[13]/.test(addr)) {
    return addr.length >= 26 && addr.length <= 35
      && /^[1-9A-HJ-NP-Za-km-z]+$/.test(addr);
  }
  return false;
}

const template = readFileSync(TEMPLATE, 'utf8');

let injectedAddress = tipAddress;
let injectedSats = tipSatsRaw ? Number(tipSatsRaw) : null;

if (!looksLikeMainnetAddress(tipAddress)) {
  const msg = tipAddress
    ? `HAUSHOPPE_TIP_ADDRESS "${tipAddress}" is not a mainnet Bitcoin address (bc1p/bc1q/1/3 prefix).`
    : 'HAUSHOPPE_TIP_ADDRESS is unset.';
  if (isCi) {
    console.error(`[inject-env] ${msg} Refusing to build.`);
    process.exit(1);
  }
  console.warn(`[inject-env] WARN: ${msg} Writing placeholder; main.ts boot-time check will refuse to start the bundle.`);
  injectedAddress = '???';
}

if (injectedSats !== null && (!Number.isInteger(injectedSats) || injectedSats < 0)) {
  console.error(`[inject-env] HAUSHOPPE_TIP_SATS "${tipSatsRaw}" is not a non-negative integer.`);
  process.exit(1);
}

let generated = template.replace(
  /haushoppeTipAddress:\s*'[^']*'/,
  `haushoppeTipAddress: '${injectedAddress}'`,
);

if (injectedSats !== null) {
  generated = generated.replace(
    /haushoppeTipSats:\s*\d+/,
    `haushoppeTipSats: ${injectedSats}`,
  );
}

const banner = `// AUTO-GENERATED by scripts/inject-env.mjs at build time. Do not edit.
// Source template: environment.prod.ts. Values overridden from CI env:
//   - HAUSHOPPE_TIP_ADDRESS
//   - HAUSHOPPE_TIP_SATS (optional)
`;

writeFileSync(OUT, banner + generated, 'utf8');

const shortAddr = injectedAddress === '???'
  ? '???'
  : `${injectedAddress.slice(0, 8)}...${injectedAddress.slice(-4)}`;
console.log(`[inject-env] wrote ${OUT} (tipAddress=${shortAddr}, tipSats=${injectedSats ?? '(from template)'})`);
