/**
 * 🎨 API
 * Serves data for our projects
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InscriptionExtended } from './inscriptionExtended';


export interface InscriptionExtendedPaginatedResult { 
    /**
     * An array of inscriptions
     */
    inscriptions: Array<InscriptionExtended>;
    /**
     * Total number of all inscriptions
     */
    totalInscriptions: number;
    itemsPerPage: number;
    currentPage: number;
}

