/**
 * 🎨 NFT API
 * Serves data for our NFT projects
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConfigDetails } from './configDetails';


export interface ConfigResponse { 
    environment: string;
    uptime: string;
    config: ConfigDetails;
}

