/**
 * 🎨 API
 * Serves data for our projects
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HtmlInscriptionRequest { 
    /**
     * A single Bitcoin address to receive the inscription
     */
    receiveAddress: string;
    /**
     * Text that should be subscribed
     */
    htmlString: string;
    /**
     * Miner fee that will be paid while inscribing the ordinals in sats/byte.
     */
    fee: number;
}

