/**
 * 🎨 API
 * Serves data for our projects
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Meta } from './meta';


/**
 * One inscription
 */
export interface InscriptionExtendedSingleResultInscription { 
    inscriptionId: string;
    inscriptionNumber: number;
    blockHeight: number;
    meta: Meta;
}

