/**
 * 🎨 API
 * Serves data for our projects
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetatdataAttributeValue } from './metatdataAttributeValue';


export interface MetatdataAttribute { 
    trait_type: string;
    value: MetatdataAttributeValue;
    display_type: string;
}

