/**
 * 🎨 NFT API
 * Serves data for our NFT projects
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetatdataAttribute } from './metatdataAttribute';


export interface Metadata { 
    description: string;
    externalUrl: string;
    image: string;
    name: string;
    attributes: Array<MetatdataAttribute>;
    tokenId: number;
}

