/**
 * 🎨 NFT API
 * Serves data for our NFT projects
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MintTicket { 
    /**
     * The hashed message, which contains msg.sender + maximumAllowedMints
     */
    messageHash: string;
    /**
     * The secret signature that only this API can create
     */
    signature: string;
    /**
     * Maximum allowed mints
     */
    maximumAllowedMints: number;
}

