/**
 * 🎨 NFT API
 * Serves data for our NFT projects
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KnownTokenResponse } from './knownTokenResponse';


export interface StatusResponse { 
    environment: string;
    uptime: string;
    knownTokens: Array<KnownTokenResponse>;
}

