/**
 * 🎨 API
 * Serves data for our projects
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TokenOwner { 
    tokenId: number;
    owner: string;
    ownerName: string;
    lender: string;
    lenderName: string;
}

