export const abi = {
  genesis: [
    "constructor()",
    "error ApprovalCallerNotOwnerNorApproved()",
    "error ApprovalQueryForNonexistentToken()",
    "error BalanceQueryForZeroAddress()",
    "error MintERC2309QuantityExceedsLimit()",
    "error MintToZeroAddress()",
    "error MintZeroQuantity()",
    "error OwnerQueryForNonexistentToken()",
    "error OwnershipNotInitializedForExtraData()",
    "error TransferCallerNotOwnerNorApproved()",
    "error TransferFromIncorrectOwner()",
    "error TransferToNonERC721ReceiverImplementer()",
    "error TransferToZeroAddress()",
    "error URIQueryForNonexistentToken()",
    "event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)",
    "event ApprovalForAll(address indexed owner, address indexed operator, bool approved)",
    "event ConsecutiveTransfer(uint256 indexed fromTokenId, uint256 toTokenId, address indexed from, address indexed to)",
    "event Loan(address indexed from, address indexed to, uint256 tokenId)",
    "event LoanRetrieved(address indexed from, address indexed to, uint256 tokenId)",
    "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
    "event Paused(address account)",
    "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
    "event Unpaused(address account)",
    "function approve(address to, uint256 tokenId) payable",
    "function balanceOf(address owner) view returns (uint256)",
    "function deleteDefaultRoyalty()",
    "function getApproved(uint256 tokenId) view returns (address)",
    "function gift(address[] receivers, uint256 mintNumber)",
    "function isApprovedForAll(address owner, address operator) view returns (bool)",
    "function isBatchMosaicMintActive() view returns (bool)",
    "function isLendingActive() view returns (bool)",
    "function isMosaic(uint256) view returns (bool)",
    "function isSaleActive() view returns (bool)",
    "function loan(uint256 tokenId, address receiver)",
    "function loanedTokensByAddress(address lender) view returns (uint256[])",
    "function maxSupply() view returns (uint256)",
    "function mint(uint256 mintNumber) payable",
    "function mintAllowlist(bytes32 messageHash, bytes signature, uint256 mintNumber, uint256 maximumAllowedMints) payable",
    "function mintMosaic(uint256 tokenId1, uint256 tokenId2, uint256 tokenId3, uint256 tokenId4) payable",
    "function mintMosaicBatch(tuple(uint256 tile1, uint256 tile2, uint256 tile3, uint256 tile4) mosaic1, tuple(uint256 tile1, uint256 tile2, uint256 tile3, uint256 tile4) mosaic2, tuple(uint256 tile1, uint256 tile2, uint256 tile3, uint256 tile4) mosaic3, tuple(uint256 tile1, uint256 tile2, uint256 tile3, uint256 tile4) mosaic4) payable",
    "function mosaics(uint256) view returns (uint256 tile1, uint256 tile2, uint256 tile3, uint256 tile4)",
    "function name() view returns (string)",
    "function owner() view returns (address)",
    "function ownerOf(uint256 tokenId) view returns (address)",
    "function pause()",
    "function paused() view returns (bool)",
    "function price() view returns (uint256)",
    "function priceForMosaic() view returns (uint256)",
    "function renounceOwnership()",
    "function resetTokenRoyalty(uint256 tokenId)",
    "function retrieveLoan(uint256 tokenId)",
    "function retrieveLoanByAdmin(uint256 tokenId)",
    "function royaltyInfo(uint256 _tokenId, uint256 _salePrice) view returns (address, uint256)",
    "function safeTransferFrom(address from, address to, uint256 tokenId) payable",
    "function safeTransferFrom(address from, address to, uint256 tokenId, bytes _data) payable",
    "function setApprovalForAll(address operator, bool approved)",
    "function setBaseURI(string baseURI)",
    "function setBaseURIForMosaic(string baseURI)",
    "function setBatchMosaicMintStatus(bool status)",
    "function setDefaultRoyalty(address receiver, uint96 feeNumerator)",
    "function setLendingStatus(bool status)",
    "function setMaxSupply(uint256 newMaxSupply)",
    "function setMintPrice(uint256 newMintPrice)",
    "function setMintPriceForMosaic(uint256 newMintPrice)",
    "function setName(string newName)",
    "function setSaleStatus(bool status)",
    "function setSignerAddress(address _signerAddress)",
    "function setSymbol(string newSymbol)",
    "function setTermsAndConditionsURI(string uri)",
    "function setTokenRoyalty(uint256 tokenId, address receiver, uint96 feeNumerator)",
    "function supportsInterface(bytes4 interfaceId) view returns (bool)",
    "function symbol() view returns (string)",
    "function termsAndConditionsURI() view returns (string)",
    "function tokenInMosaic(uint256) view returns (bool)",
    "function tokenOwnersOnLoan(uint256) view returns (address)",
    "function tokenURI(uint256 tokenId) view returns (string)",
    "function totalLoaned() view returns (uint256)",
    "function totalLoanedPerAddress(address) view returns (uint256)",
    "function totalMintsPerAddress(address) view returns (uint256)",
    "function totalSupply() view returns (uint256)",
    "function transferFrom(address from, address to, uint256 tokenId) payable",
    "function transferOwnership(address newOwner)",
    "function unpause()",
    "function withdraw()",
    "function withdrawTo(address to, uint256 amount)"
  ],
  mosaic: [
    "constructor()",
    "error ApprovalCallerNotOwnerNorApproved()",
    "error ApprovalQueryForNonexistentToken()",
    "error BalanceQueryForZeroAddress()",
    "error MintERC2309QuantityExceedsLimit()",
    "error MintToZeroAddress()",
    "error MintZeroQuantity()",
    "error OwnerQueryForNonexistentToken()",
    "error OwnershipNotInitializedForExtraData()",
    "error TransferCallerNotOwnerNorApproved()",
    "error TransferFromIncorrectOwner()",
    "error TransferToNonERC721ReceiverImplementer()",
    "error TransferToZeroAddress()",
    "error URIQueryForNonexistentToken()",
    "event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)",
    "event ApprovalForAll(address indexed owner, address indexed operator, bool approved)",
    "event ConsecutiveTransfer(uint256 indexed fromTokenId, uint256 toTokenId, address indexed from, address indexed to)",
    "event Loan(address indexed from, address indexed to, uint256 tokenId)",
    "event LoanRetrieved(address indexed from, address indexed to, uint256 tokenId)",
    "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
    "event Paused(address account)",
    "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
    "event Unpaused(address account)",
    "function approve(address to, uint256 tokenId) payable",
    "function balanceOf(address owner) view returns (uint256)",
    "function deleteDefaultRoyalty()",
    "function getApproved(uint256 tokenId) view returns (address)",
    "function gift(address[] receivers, uint256 mintNumber)",
    "function isApprovedForAll(address owner, address operator) view returns (bool)",
    "function isBatchMosaicMintActive() view returns (bool)",
    "function isLendingActive() view returns (bool)",
    "function isMosaic(uint256) view returns (bool)",
    "function isSaleActive() view returns (bool)",
    "function loan(uint256 tokenId, address receiver)",
    "function loanedTokensByAddress(address lender) view returns (uint256[])",
    "function maxSupply() view returns (uint256)",
    "function mint(uint256 mintNumber) payable",
    "function mintAllowlist(bytes32 messageHash, bytes signature, uint256 mintNumber, uint256 maximumAllowedMints) payable",
    "function mintMosaic(uint256 tokenId1, uint256 tokenId2, uint256 tokenId3, uint256 tokenId4) payable",
    "function mintMosaicBatch(tuple(uint256 tile1, uint256 tile2, uint256 tile3, uint256 tile4) mosaic1, tuple(uint256 tile1, uint256 tile2, uint256 tile3, uint256 tile4) mosaic2, tuple(uint256 tile1, uint256 tile2, uint256 tile3, uint256 tile4) mosaic3, tuple(uint256 tile1, uint256 tile2, uint256 tile3, uint256 tile4) mosaic4) payable",
    "function mosaics(uint256) view returns (uint256 tile1, uint256 tile2, uint256 tile3, uint256 tile4)",
    "function name() view returns (string)",
    "function owner() view returns (address)",
    "function ownerOf(uint256 tokenId) view returns (address)",
    "function pause()",
    "function paused() view returns (bool)",
    "function price() view returns (uint256)",
    "function priceForMosaic() view returns (uint256)",
    "function renounceOwnership()",
    "function resetTokenRoyalty(uint256 tokenId)",
    "function retrieveLoan(uint256 tokenId)",
    "function retrieveLoanByAdmin(uint256 tokenId)",
    "function royaltyInfo(uint256 _tokenId, uint256 _salePrice) view returns (address, uint256)",
    "function safeTransferFrom(address from, address to, uint256 tokenId) payable",
    "function safeTransferFrom(address from, address to, uint256 tokenId, bytes _data) payable",
    "function setApprovalForAll(address operator, bool approved)",
    "function setBaseURI(string baseURI)",
    "function setBaseURIForMosaic(string baseURI)",
    "function setBatchMosaicMintStatus(bool status)",
    "function setDefaultRoyalty(address receiver, uint96 feeNumerator)",
    "function setLendingStatus(bool status)",
    "function setMaxSupply(uint256 newMaxSupply)",
    "function setMintPrice(uint256 newMintPrice)",
    "function setMintPriceForMosaic(uint256 newMintPrice)",
    "function setName(string newName)",
    "function setSaleStatus(bool status)",
    "function setSignerAddress(address _signerAddress)",
    "function setSymbol(string newSymbol)",
    "function setTermsAndConditionsURI(string uri)",
    "function setTokenRoyalty(uint256 tokenId, address receiver, uint96 feeNumerator)",
    "function supportsInterface(bytes4 interfaceId) view returns (bool)",
    "function symbol() view returns (string)",
    "function termsAndConditionsURI() view returns (string)",
    "function tokenInMosaic(uint256) view returns (bool)",
    "function tokenOwnersOnLoan(uint256) view returns (address)",
    "function tokenURI(uint256 tokenId) view returns (string)",
    "function totalLoaned() view returns (uint256)",
    "function totalLoanedPerAddress(address) view returns (uint256)",
    "function totalMintsPerAddress(address) view returns (uint256)",
    "function totalSupply() view returns (uint256)",
    "function transferFrom(address from, address to, uint256 tokenId) payable",
    "function transferOwnership(address newOwner)",
    "function unpause()",
    "function withdraw()",
    "function withdrawTo(address to, uint256 amount)"
  ],
  sea: [
    "constructor()",
    "error ApprovalCallerNotOwnerNorApproved()",
    "error ApprovalQueryForNonexistentToken()",
    "error BalanceQueryForZeroAddress()",
    "error MintERC2309QuantityExceedsLimit()",
    "error MintToZeroAddress()",
    "error MintZeroQuantity()",
    "error OwnerQueryForNonexistentToken()",
    "error OwnershipNotInitializedForExtraData()",
    "error TransferCallerNotOwnerNorApproved()",
    "error TransferFromIncorrectOwner()",
    "error TransferToNonERC721ReceiverImplementer()",
    "error TransferToZeroAddress()",
    "error URIQueryForNonexistentToken()",
    "event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)",
    "event ApprovalForAll(address indexed owner, address indexed operator, bool approved)",
    "event ConsecutiveTransfer(uint256 indexed fromTokenId, uint256 toTokenId, address indexed from, address indexed to)",
    "event Loan(address indexed from, address indexed to, uint256 tokenId)",
    "event LoanRetrieved(address indexed from, address indexed to, uint256 tokenId)",
    "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
    "event Paused(address account)",
    "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
    "event Unpaused(address account)",
    "function approve(address to, uint256 tokenId) payable",
    "function balanceOf(address owner) view returns (uint256)",
    "function deleteDefaultRoyalty()",
    "function getApproved(uint256 tokenId) view returns (address)",
    "function gift(address[] receivers, uint256 mintNumber)",
    "function isApprovedForAll(address owner, address operator) view returns (bool)",
    "function isLendingActive() view returns (bool)",
    "function isSaleActive() view returns (bool)",
    "function loan(uint256 tokenId, address receiver)",
    "function loanedTokensByAddress(address lender) view returns (uint256[])",
    "function maxSupply() view returns (uint256)",
    "function mint(uint256 mintNumber) payable",
    "function mintAllowlist(bytes32 messageHash, bytes signature, uint256 mintNumber, uint256 maximumAllowedMints) payable",
    "function name() view returns (string)",
    "function owner() view returns (address)",
    "function ownerOf(uint256 tokenId) view returns (address)",
    "function pause()",
    "function paused() view returns (bool)",
    "function price() view returns (uint256)",
    "function renounceOwnership()",
    "function resetTokenRoyalty(uint256 tokenId)",
    "function retrieveLoan(uint256 tokenId)",
    "function retrieveLoanByAdmin(uint256 tokenId)",
    "function royaltyInfo(uint256 _tokenId, uint256 _salePrice) view returns (address, uint256)",
    "function safeTransferFrom(address from, address to, uint256 tokenId) payable",
    "function safeTransferFrom(address from, address to, uint256 tokenId, bytes _data) payable",
    "function setApprovalForAll(address operator, bool approved)",
    "function setBaseURI(string baseURI)",
    "function setDefaultRoyalty(address receiver, uint96 feeNumerator)",
    "function setLendingStatus(bool status)",
    "function setMaxSupply(uint256 newMaxSupply)",
    "function setMintPrice(uint256 newMintPrice)",
    "function setName(string newName)",
    "function setSaleStatus(bool status)",
    "function setSignerAddress(address _signerAddress)",
    "function setSymbol(string newSymbol)",
    "function setTermsAndConditionsURI(string uri)",
    "function setTokenRoyalty(uint256 tokenId, address receiver, uint96 feeNumerator)",
    "function supportsInterface(bytes4 interfaceId) view returns (bool)",
    "function symbol() view returns (string)",
    "function termsAndConditionsURI() view returns (string)",
    "function tokenOwnersOnLoan(uint256) view returns (address)",
    "function tokenURI(uint256 tokenId) view returns (string)",
    "function totalLoaned() view returns (uint256)",
    "function totalLoanedPerAddress(address) view returns (uint256)",
    "function totalMintsPerAddress(address) view returns (uint256)",
    "function totalSupply() view returns (uint256)",
    "function transferFrom(address from, address to, uint256 tokenId) payable",
    "function transferOwnership(address newOwner)",
    "function unpause()",
    "function withdraw()",
    "function withdrawTo(address to, uint256 amount)"
  ],
  art: [
    "constructor()",
    "error ApprovalCallerNotOwnerNorApproved()",
    "error ApprovalQueryForNonexistentToken()",
    "error BalanceQueryForZeroAddress()",
    "error MintERC2309QuantityExceedsLimit()",
    "error MintToZeroAddress()",
    "error MintZeroQuantity()",
    "error OwnerQueryForNonexistentToken()",
    "error OwnershipNotInitializedForExtraData()",
    "error TransferCallerNotOwnerNorApproved()",
    "error TransferFromIncorrectOwner()",
    "error TransferToNonERC721ReceiverImplementer()",
    "error TransferToZeroAddress()",
    "error URIQueryForNonexistentToken()",
    "event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)",
    "event ApprovalForAll(address indexed owner, address indexed operator, bool approved)",
    "event ConsecutiveTransfer(uint256 indexed fromTokenId, uint256 toTokenId, address indexed from, address indexed to)",
    "event Loan(address indexed from, address indexed to, uint256 tokenId)",
    "event LoanRetrieved(address indexed from, address indexed to, uint256 tokenId)",
    "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
    "event Paused(address account)",
    "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
    "event Unpaused(address account)",
    "function approve(address to, uint256 tokenId) payable",
    "function balanceOf(address owner) view returns (uint256)",
    "function deleteDefaultRoyalty()",
    "function getApproved(uint256 tokenId) view returns (address)",
    "function gift(address[] receivers, uint256 mintNumber)",
    "function isApprovedForAll(address owner, address operator) view returns (bool)",
    "function isLendingActive() view returns (bool)",
    "function isSaleActive() view returns (bool)",
    "function loan(uint256 tokenId, address receiver)",
    "function loanedTokensByAddress(address lender) view returns (uint256[])",
    "function maxSupply() view returns (uint256)",
    "function mint(uint256 mintNumber) payable",
    "function mintAllowlist(bytes32 messageHash, bytes signature, uint256 mintNumber, uint256 maximumAllowedMints) payable",
    "function name() view returns (string)",
    "function owner() view returns (address)",
    "function ownerOf(uint256 tokenId) view returns (address)",
    "function pause()",
    "function paused() view returns (bool)",
    "function price() view returns (uint256)",
    "function renounceOwnership()",
    "function resetTokenRoyalty(uint256 tokenId)",
    "function retrieveLoan(uint256 tokenId)",
    "function retrieveLoanByAdmin(uint256 tokenId)",
    "function royaltyInfo(uint256 _tokenId, uint256 _salePrice) view returns (address, uint256)",
    "function safeTransferFrom(address from, address to, uint256 tokenId) payable",
    "function safeTransferFrom(address from, address to, uint256 tokenId, bytes _data) payable",
    "function setApprovalForAll(address operator, bool approved)",
    "function setBaseURI(string baseURI)",
    "function setDefaultRoyalty(address receiver, uint96 feeNumerator)",
    "function setLendingStatus(bool status)",
    "function setMaxSupply(uint256 newMaxSupply)",
    "function setMintPrice(uint256 newMintPrice)",
    "function setName(string newName)",
    "function setSaleStatus(bool status)",
    "function setSignerAddress(address _signerAddress)",
    "function setSymbol(string newSymbol)",
    "function setTermsAndConditionsURI(string uri)",
    "function setTokenRoyalty(uint256 tokenId, address receiver, uint96 feeNumerator)",
    "function supportsInterface(bytes4 interfaceId) view returns (bool)",
    "function symbol() view returns (string)",
    "function termsAndConditionsURI() view returns (string)",
    "function tokenOwnersOnLoan(uint256) view returns (address)",
    "function tokenURI(uint256 tokenId) view returns (string)",
    "function totalLoaned() view returns (uint256)",
    "function totalLoanedPerAddress(address) view returns (uint256)",
    "function totalMintsPerAddress(address) view returns (uint256)",
    "function totalSupply() view returns (uint256)",
    "function transferFrom(address from, address to, uint256 tokenId) payable",
    "function transferOwnership(address newOwner)",
    "function unpause()",
    "function withdraw()",
    "function withdrawTo(address to, uint256 amount)"
  ],
  artist: [
    "constructor()",
    "error ApprovalCallerNotOwnerNorApproved()",
    "error ApprovalQueryForNonexistentToken()",
    "error BalanceQueryForZeroAddress()",
    "error MintERC2309QuantityExceedsLimit()",
    "error MintToZeroAddress()",
    "error MintZeroQuantity()",
    "error OwnerQueryForNonexistentToken()",
    "error OwnershipNotInitializedForExtraData()",
    "error TransferCallerNotOwnerNorApproved()",
    "error TransferFromIncorrectOwner()",
    "error TransferToNonERC721ReceiverImplementer()",
    "error TransferToZeroAddress()",
    "error URIQueryForNonexistentToken()",
    "event Agreement(address indexed from, bool agreement)",
    "event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)",
    "event ApprovalForAll(address indexed owner, address indexed operator, bool approved)",
    "event ConsecutiveTransfer(uint256 indexed fromTokenId, uint256 toTokenId, address indexed from, address indexed to)",
    "event Loan(address indexed from, address indexed to, uint256 tokenId)",
    "event LoanRetrieved(address indexed from, address indexed to, uint256 tokenId)",
    "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
    "event Paused(address account)",
    "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
    "event Unpaused(address account)",
    "function agreeOrDisagreeToTermsAndConditions(bool agreement)",
    "function agreements(address) view returns (bool)",
    "function approve(address to, uint256 tokenId) payable",
    "function balanceOf(address owner) view returns (uint256)",
    "function deleteDefaultRoyalty()",
    "function getApproved(uint256 tokenId) view returns (address)",
    "function gift(address[] receivers, uint256 mintNumber)",
    "function isApprovedForAll(address owner, address operator) view returns (bool)",
    "function isLendingActive() view returns (bool)",
    "function isSaleActive() view returns (bool)",
    "function loan(uint256 tokenId, address receiver)",
    "function loanedTokensByAddress(address lender) view returns (uint256[])",
    "function maxSupply() view returns (uint256)",
    "function mint(uint256 mintNumber) payable",
    "function mintAllowlist(bytes32 messageHash, bytes signature, uint256 mintNumber, uint256 maximumAllowedMints) payable",
    "function name() view returns (string)",
    "function owner() view returns (address)",
    "function ownerOf(uint256 tokenId) view returns (address)",
    "function pause()",
    "function paused() view returns (bool)",
    "function price() view returns (uint256)",
    "function renounceOwnership()",
    "function resetTokenRoyalty(uint256 tokenId)",
    "function retrieveLoan(uint256 tokenId)",
    "function retrieveLoanByAdmin(uint256 tokenId)",
    "function royaltyInfo(uint256 _tokenId, uint256 _salePrice) view returns (address, uint256)",
    "function safeTransferFrom(address from, address to, uint256 tokenId) payable",
    "function safeTransferFrom(address from, address to, uint256 tokenId, bytes _data) payable",
    "function setApprovalForAll(address operator, bool approved)",
    "function setBaseURI(string baseURI)",
    "function setDefaultRoyalty(address receiver, uint96 feeNumerator)",
    "function setLendingStatus(bool status)",
    "function setMaxSupply(uint256 newMaxSupply)",
    "function setMintPrice(uint256 newMintPrice)",
    "function setName(string newName)",
    "function setSaleStatus(bool status)",
    "function setSignerAddress(address _signerAddress)",
    "function setSymbol(string newSymbol)",
    "function setTermsAndConditionsURI(string uri)",
    "function setTokenRoyalty(uint256 tokenId, address receiver, uint96 feeNumerator)",
    "function supportsInterface(bytes4 interfaceId) view returns (bool)",
    "function symbol() view returns (string)",
    "function termsAndConditionsURI() view returns (string)",
    "function tokenOwnersOnLoan(uint256) view returns (address)",
    "function tokenURI(uint256 tokenId) view returns (string)",
    "function totalLoaned() view returns (uint256)",
    "function totalLoanedPerAddress(address) view returns (uint256)",
    "function totalMintsPerAddress(address) view returns (uint256)",
    "function totalSupply() view returns (uint256)",
    "function transferFrom(address from, address to, uint256 tokenId) payable",
    "function transferOwnership(address newOwner)",
    "function unpause()",
    "function withdraw()",
    "function withdrawTo(address to, uint256 amount)"
  ],
  cube: [
    "constructor()",
    "error ApprovalCallerNotOwnerNorApproved()",
    "error ApprovalQueryForNonexistentToken()",
    "error BalanceQueryForZeroAddress()",
    "error MintERC2309QuantityExceedsLimit()",
    "error MintToZeroAddress()",
    "error MintZeroQuantity()",
    "error OwnerQueryForNonexistentToken()",
    "error OwnershipNotInitializedForExtraData()",
    "error TransferCallerNotOwnerNorApproved()",
    "error TransferFromIncorrectOwner()",
    "error TransferToNonERC721ReceiverImplementer()",
    "error TransferToZeroAddress()",
    "error URIQueryForNonexistentToken()",
    "event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)",
    "event ApprovalForAll(address indexed owner, address indexed operator, bool approved)",
    "event ConsecutiveTransfer(uint256 indexed fromTokenId, uint256 toTokenId, address indexed from, address indexed to)",
    "event Loan(address indexed from, address indexed to, uint256 tokenId)",
    "event LoanRetrieved(address indexed from, address indexed to, uint256 tokenId)",
    "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
    "event Paused(address account)",
    "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
    "event Unpaused(address account)",
    "function approve(address to, uint256 tokenId) payable",
    "function balanceOf(address owner) view returns (uint256)",
    "function deleteDefaultRoyalty()",
    "function getApproved(uint256 tokenId) view returns (address)",
    "function gift(address[] receivers, uint256 mintNumber)",
    "function isApprovedForAll(address owner, address operator) view returns (bool)",
    "function isLendingActive() view returns (bool)",
    "function isSaleActive() view returns (bool)",
    "function loan(uint256 tokenId, address receiver)",
    "function loanedTokensByAddress(address lender) view returns (uint256[])",
    "function maxSupply() view returns (uint256)",
    "function mint(uint256 mintNumber) payable",
    "function mintAllowlist(bytes32 messageHash, bytes signature, uint256 mintNumber, uint256 maximumAllowedMints) payable",
    "function name() view returns (string)",
    "function owner() view returns (address)",
    "function ownerOf(uint256 tokenId) view returns (address)",
    "function pause()",
    "function paused() view returns (bool)",
    "function price() view returns (uint256)",
    "function renounceOwnership()",
    "function resetTokenRoyalty(uint256 tokenId)",
    "function retrieveLoan(uint256 tokenId)",
    "function retrieveLoanByAdmin(uint256 tokenId)",
    "function royaltyInfo(uint256 _tokenId, uint256 _salePrice) view returns (address, uint256)",
    "function safeTransferFrom(address from, address to, uint256 tokenId) payable",
    "function safeTransferFrom(address from, address to, uint256 tokenId, bytes _data) payable",
    "function setApprovalForAll(address operator, bool approved)",
    "function setBaseURI(string baseURI)",
    "function setDefaultRoyalty(address receiver, uint96 feeNumerator)",
    "function setLendingStatus(bool status)",
    "function setMaxSupply(uint256 newMaxSupply)",
    "function setMintPrice(uint256 newMintPrice)",
    "function setName(string newName)",
    "function setSaleStatus(bool status)",
    "function setSignerAddress(address _signerAddress)",
    "function setSymbol(string newSymbol)",
    "function setTermsAndConditionsURI(string uri)",
    "function setTokenRoyalty(uint256 tokenId, address receiver, uint96 feeNumerator)",
    "function supportsInterface(bytes4 interfaceId) view returns (bool)",
    "function symbol() view returns (string)",
    "function termsAndConditionsURI() view returns (string)",
    "function tokenOwnersOnLoan(uint256) view returns (address)",
    "function tokenURI(uint256 tokenId) view returns (string)",
    "function totalLoaned() view returns (uint256)",
    "function totalLoanedPerAddress(address) view returns (uint256)",
    "function totalMintsPerAddress(address) view returns (uint256)",
    "function totalSupply() view returns (uint256)",
    "function transferFrom(address from, address to, uint256 tokenId) payable",
    "function transferOwnership(address newOwner)",
    "function unpause()",
    "function withdraw()",
    "function withdrawTo(address to, uint256 amount)"
  ]
};
