name: Build Cube API

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cube-workspace

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - run: npm install
    - run: npm run build
    - run: cp package-heroku.json dist/apps/backend/package.json
    - name: Deploy API to cube-api-build repo
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npx angular-cli-ghpages --repo=https://github.com/haushoppe/cube-website-build.git --branch=main --dir=dist/apps/backend --name="The Buildbot" --email=noreply@haushoppe.art

