name: Build & deploy API

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - run: npm install
    - run: npm run build
    - run: cp package-api-compiled.json dist/apps/backend/package.json
    - name: Deploy API with compiled code to `build-api` branch
      run: |
        npx angular-cli-ghpages --branch=build-api --dir=dist/apps/backend --no-silent --name="The Buildbot" --email=noreply@haushoppe.art

